apiVersion: v1
kind: Service
metadata:
  name: infer-vllm
  namespace: default
spec:
  type: NodePort
  selector:
    app: infer-vllm
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer-vllm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infer-vllm
  template:
    metadata:
      labels:
        app: infer-vllm
    spec:
      containers:
      - name: api
        image: your-registry/vllm:latest
        ports:
        - containerPort: 9000
        env:
        - name: MODEL
          value: qwen3-32b

