repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "ci / gate"
          - "codex-review / review"
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
