name: auto-merge

on:
  # 手动触发时才启用自动合并（默认关闭）
  workflow_dispatch:

jobs:
  enable-auto-merge:
    name: enable-auto-merge
    # Only for PRs from this repository (not forks) and not drafts
    if: >-
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge (rebase)
        id: enable_rebase
        uses: peter-evans/enable-pull-request-automerge@v3
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
      - name: Enable auto-merge (squash fallback)
        if: steps.enable_rebase.outcome == 'failure'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
