name: auto-merge

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  enable-auto-merge:
    name: enable-auto-merge
    # Only for PRs from this repository (not forks) and not drafts
    if: >-
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge on the PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

