name: Repo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    name: Validate YAML (configs/.github)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: |
          yamllint -c .yamllint.yaml .

  repo-structure:
    name: Repository Structure Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          set -euo pipefail
          require() { [ -e "$1" ] || { echo "Missing: $1"; exit 1; }; }
          require AGENTS.md
          require docs/DESIGN.md
          require docs/DEVELOPMENT.md
          require docs/REQUIREMENTS.md
          require docs/TODO.md
          require configs/providers.yaml
          require configs/matrix.yaml
          echo "All required files present."

