name: daily

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Skip Pushgateway push'
        required: false
        default: 'false'
        type: boolean

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    if: github.repository == 'dgy516/vllm_cibench'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - name: Run daily matrix
        env:
          PROM_PUSHGATEWAY_URL: ${{ secrets.PROM_PUSHGATEWAY_URL }}
        run: |
          ARGS=""
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            ARGS="--dry-run"
          fi
          python -m vllm_cibench.run run-matrix --run-type daily $ARGS
