name: daily

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Skip Pushgateway push'
        required: false
        default: 'false'

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - name: Run daily matrix
        env:
          PROM_PUSHGATEWAY_URL: ${{ secrets.PROM_PUSHGATEWAY_URL }}
          DRY_RUN: ${{ github.event.inputs.dry-run }}
          IS_FORK: ${{ github.event.repository.fork }}
        run: |
          if [[ -z "$PROM_PUSHGATEWAY_URL" || "$IS_FORK" == "true" || "$DRY_RUN" == "true" ]]; then
            python -m vllm_cibench.run run-matrix --run-type daily --dry-run
          else
            python -m vllm_cibench.run run-matrix --run-type daily
          fi
