name: Daily Matrix Run

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 00:00 (Asia/Shanghai 08:00)
  workflow_dispatch: {}

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest mypy

      - name: Placeholder run (to be replaced with orchestrator)
        run: |
          echo "Daily workflow scaffold. Replace with scenario orchestrator when implemented."

      - name: Upload artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: daily-artifacts
          path: |
            artifacts/**
          if-no-files-found: ignore

