name: Protect main from direct pushes

on:
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Check pusher
        run: |
          echo "Pusher: ${{ github.event.pusher.name }}"
          # GitHub PR merges are pushed by 'web-flow'. Any other pusher means direct push.
          if [ "${{ github.event.pusher.name }}" != "web-flow" ]; then
            echo "Direct pushes to main are forbidden. Please open a Pull Request."
            exit 1
          fi
          echo "Push comes from a PR merge (web-flow). Allowed."

